import Head from 'next/head'
import axios from 'axios';
import Form from 'components/Form'

export default function Home({ data }) {
  return (
    <div>
      <Head>
        <title>Cura Healthcare | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Form data={data} />
      </main>
    </div>
  )
}

export const getServerSideProps = async context => {
  const res = await axios.get("https://cura-front-end-test.herokuapp.com/")
  const data = res.data;
  return {
    props: {
      data
    }
  }
}
